baseURL: "https://nutchi.net"
title: ぬっちのぽえむ
languageCode: ja-jp
theme: PaperMod

params:
  title: ぬっちのぽえむ
  keywords: [ blog ]
  ShowReadingTime: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: ぬっちのぽえむ
    Content: 色々やったことの備忘録。ポエムはたぶん書きません。

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
