baseURL: "https://nutchi.net"
title: ぬっちのぽえむ
languageCode: ja-jp
theme: PaperMod
enableRobotsTXT: true

params:
  description: 色々やったことの備忘録。ポエムはたぶん書きません。
  keywords: [ blog ]
  ShowReadingTime: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: ぬっちのぽえむ
    Content: 色々やったことの備忘録。ポエムはたぶん書きません。

menu:
  main:
    - identifier: profile
      name: Profile
      url: /posts/202304211951/
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
