baseURL: "https://nutchi.net"
title: ぬっちのぽえむ
languageCode: ja-jp
theme: PaperMod

params:
  title: ぬっちのぽえむ
  keywords: [ blog ]
  ShowReadingTime: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: ぬっちのぽえむ
    Content: 色々やったことの備忘録。ポエムはたぶん書きません。

      # socialIcons:
      #   - name: GitHub
      #     url: "https://github.com/tsuoihito"
      #   - name: Twitter
      #     url: "https://twitter.com/tsuoihito"

      # editPost:
      #   URL: "https://github.com/tsuoihito/tsuoihito.github.io/content"
      #   Text: "Suggest Changes"
      #   appendFilePath: true

menu:
  main:
    - identifier: post
      name: Post
      url: /post/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
